### ISSUE TITLE
Element/tag syntax

### ISSUE THREAD

**Issue by aubreywullschleger** [SherylCv/tea_cozy#1]
Subtlety for errors!  Line 9 you have a semicolon that should be a `>` mark instead.

https://github.com/SherylCv/tea_cozy/blob/master/index.html#L9

**Comment by SherylCv** [comment]
Yikes....that's one of my worst coding traits...and I never find that stuff until I'm ready to tear my hair out because something isn't working properly :)

**Comment by SherylCv** [comment]
Got this corrected now :) Thanks.
