### ISSUE TITLE
Using locally stored images

### ISSUE THREAD

**Issue by aubreywullschleger** [SherylCv/tea_cozy#2]
Great! Nice job using locally stored images for your project. This is best practice for production code and helps your page load faster. 

Example: https://github.com/SherylCv/tea_cozy/blob/master/index.html#L35

Make sure to use descriptive `alt` attributes on your `<img>` elements like this: `<img src="./resources/images/img-berryblitz.jpg" alt="grey mug of tea with berries">` This is best practice and helps make your site more accessible!

**Comment by SherylCv** [comment]
Thank you.
